/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Alternative': RouteRecordInfo<'/Alternative', '/Alternative', Record<never, never>, Record<never, never>>,
    '/Criteria': RouteRecordInfo<'/Criteria', '/Criteria', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/ScoringData': RouteRecordInfo<'/ScoringData', '/ScoringData', Record<never, never>, Record<never, never>>,
    '/SubCriteria': RouteRecordInfo<'/SubCriteria', '/SubCriteria', Record<never, never>, Record<never, never>>,
    '/TeamManagement': RouteRecordInfo<'/TeamManagement', '/TeamManagement', Record<never, never>, Record<never, never>>,
    '/TopsisScore': RouteRecordInfo<'/TopsisScore', '/TopsisScore', Record<never, never>, Record<never, never>>,
  }
}
