"""initial tables

Revision ID: 255cf0fd82ce
Revises: 71aef01d494d
Create Date: 2025-09-19 14:03:57.429161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '255cf0fd82ce'
down_revision = '71aef01d494d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_alt', sa.String(length=50), nullable=True))
        batch_op.drop_column('nip')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nip', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('id_alt')

    # ### end Alembic commands ###
