"""foregn key user_id in project

Revision ID: 5c2c27fc82c4
Revises: d51ddfcadf1e
Create Date: 2025-10-01 15:51:41.115426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2c27fc82c4'
down_revision = 'd51ddfcadf1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
