"""initial tables

Revision ID: 71aef01d494d
Revises: e7542801b55a
Create Date: 2025-09-19 09:47:18.894990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71aef01d494d'
down_revision = 'e7542801b55a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nip', sa.String(length=50), nullable=True))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.drop_column('nip')

    # ### end Alembic commands ###
