"""initial tables

Revision ID: c305ca6d66a9
Revises: 255cf0fd82ce
Create Date: 2025-09-19 15:57:34.428614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c305ca6d66a9'
down_revision = '255cf0fd82ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topsis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('alternative_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.drop_column('rank')

    op.drop_table('topsis_results')
    # ### end Alembic commands ###
