"""add cascade delete to foreign keys

Revision ID: e997638e40c7
Revises: c305ca6d66a9
Create Date: 2025-09-30 09:48:03.317955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e997638e40c7'
down_revision = 'c305ca6d66a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alternatives_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('rank')

    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('criteria_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('scores_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('scores_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'alternatives', ['alternative_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'criteria', ['criteria_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scores_ibfk_1'), 'alternatives', ['alternative_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('scores_ibfk_2'), 'criteria', ['criteria_id'], ['id'])

    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('criteria_ibfk_1'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('alternatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alternatives_ibfk_1'), 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
